package com.debjitpal.jobportal.domain;

public enum CompanyType {
    SOLE_PROPRIETORSHIP,
    PARTNERSHIP,
    LIMITED_LIABILITY_PARTNERSHIP,
    LIMITED_LIABILITY_COMPANY,
    PRIVATE_LIMITED_COMPANY,
    PUBLIC_LIMITED_COMPANY,
    CORPORATION,
    S_CORPORATION,
    C_CORPORATION,
    JOINT_STOCK_COMPANY,
    JOINT_VENTURE,
    COOPERATIVE,
    NON_PROFIT_ORGANIZATION,
    GOVERNMENT_OWNED_COMPANY,
    STATE_OWNED_ENTERPRISE,
    PUBLIC_SECTOR_UNDERTAKING,
    FOREIGN_COMPANY,
    BRANCH_OFFICE,
    SUBSIDIARY,
    HOLDING_COMPANY,
    MULTINATIONAL_CORPORATION,
    STARTUP,
    OTHER
}
