package com.debjitpal.jobportal.domain;

public enum IndustryType {
    TECHNOLOGY,
    FINANCE_BANKING,
    HEALTHCARE,
    EDUCATION,
    MANUFACTURING,
    RETAIL,
    HOSPITALITY,
    TRANSPORTATION,
    ENERGY,
    AGRICULTURE,
    REAL_ESTATE,
    TELECOMMUNICATIONS,
    ENTERTAINMENT,
    TRANSPORTATION_LOGISTICS,
    CONSULTING,
    LEGAL_SERVICES,
    AUTOMOTIVE,
    PHARMACEUTICALS,
    CONSTRUCTION,
    HUMAN_RESOURCES,
    MARKETING_ADVERTISING,
    OTHER
}
